services:
  postgres:
    # Use wal-g enhanced image when BACKUP_MODE=wal, otherwise use standard image
    image: ${POSTGRES_IMAGE:-pgvector/pgvector:pg17}
    build:
      context: .
      dockerfile: ${POSTGRES_DOCKERFILE:-}
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BACKUP_MODE: ${BACKUP_MODE:-sql}
      # wal-g environment variables (only used when BACKUP_MODE=wal)
      WALG_SSH_PREFIX: ${WALG_SSH_PREFIX:-}
      WALG_SSH_PRIVATE_KEY: ${WALG_SSH_PRIVATE_KEY:-}
      WALG_SSH_PRIVATE_KEY_PATH: ${WALG_SSH_PRIVATE_KEY_PATH:-}
      WALG_COMPRESSION_METHOD: ${WALG_COMPRESSION_METHOD:-lz4}
      WALG_DELTA_MAX_STEPS: ${WALG_DELTA_MAX_STEPS:-7}
      WALG_DELTA_ORIGIN: ${WALG_DELTA_ORIGIN:-LATEST}
      WALG_LOG_LEVEL: ${WALG_LOG_LEVEL:-INFO}
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Conditionally mount SSH key (create empty file if not exists)
      - ${SSH_KEY_PATH:-./secrets/walg_ssh_key}:/secrets/walg_ssh_key:ro
    networks:
      - pg_network

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data:${BACKUP_VOLUME_MODE:-rw}
      # Mount SSH key for wal-g mode
      - ${SSH_KEY_PATH:-./secrets/walg_ssh_key}:/secrets/walg_ssh_key:ro
    depends_on:
      - postgres
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      # Keep pgAdmin port exposed so YOU can access it from your browser
      - "127.0.0.1:8080:80"
    volumes:
      # Persist pgAdmin data and configuration
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_DISABLE_POSTFIX=true
    depends_on:
      - postgres
    networks:
      # Ensure pgAdmin is on the same network with postgres
      - pg_network

volumes:
  pg_data:
    name: postgres-data  # Named volume for clarity
  pgadmin_data:
    name: pgadmin-data  # Named volume for pgAdmin data

networks:
  pg_network:
    driver: bridge
    name: postgres-network  # More standard naming
