services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  backup:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    networks:
      - pg_network

  adminer:
    image: wodby/adminer:latest
    restart: always
    ports:
      # Keep Adminer port exposed so YOU can access it from your browser
      - "127.0.0.1:8080:9000"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres  # Updated to match database container name
    depends_on:
      - postgres
    networks:
      # Ensure adminer is on the same network with postgres
      - pg_network

volumes:
  pg_data:
    name: postgres-data  # Named volume for clarity

networks:
  pg_network:
    driver: bridge
    name: postgres-network  # More standard naming
