services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      # Expose PostgreSQL port for direct connections
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  backup:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    networks:
      - pg_network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      # Keep CloudBeaver port exposed so YOU can access it from your browser
      - "127.0.0.1:8080:8978"
    volumes:
      # Persist CloudBeaver workspace and configuration
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      # Pass PostgreSQL credentials for connection template
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      # Ensure cloudbeaver is on the same network with postgres
      - pg_network

volumes:
  pg_data:
    name: postgres-data  # Named volume for clarity
  cloudbeaver_data:
    name: cloudbeaver-data  # Named volume for CloudBeaver workspace

networks:
  pg_network:
    driver: bridge
    name: postgres-network  # More standard naming
