services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  backup:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    networks:
      - pg_network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
      - ./cloudbeaver_init/:/opt/cloudbeaver/workspace/.CloudBeaver_init:ro
    environment:
      - CB_ADMIN_NAME=${CB_ADMIN_NAME:-admin}
      - CB_ADMIN_PASSWORD=${CB_ADMIN_PASSWORD:-admin}
      - CB_SERVER_CONFIG_FILE=/opt/cloudbeaver/workspace/.CloudBeaver_init/cloudbeaver.conf
    depends_on:
      - postgres
    networks:
      - pg_network

volumes:
  pg_data:
    name: postgres-data
  cloudbeaver_data:
    name: cloudbeaver-data

networks:
  pg_network:
    driver: bridge
    name: postgres-network
