services:
  database:
    build: .
    container_name: postgres-backup  # Using kebab-case is more standard in Docker
    restart: always
    # Environment variables are now loaded from the .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "-c config_file=/etc/postgresql/postgresql.conf"
      RCLONE_CONFIG_BASE64: ${RCLONE_CONFIG_BASE64}
      AGE_PUBLIC_KEY: ${AGE_PUBLIC_KEY}
      REMOTE_PATH: ${REMOTE_PATH}
      TZ: ${TZ}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      SQL_BACKUP_RETAIN_DAYS: ${SQL_BACKUP_RETAIN_DAYS:-7}  # Added with default
    volumes:
      # Data volume
      - pg_data:/var/lib/postgresql/data
      # Config file mounts
      - ./pg_config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      # Ensure postgres is on the shared network
      - pg_network

  adminer:
    image: wodby/adminer:latest
    restart: always
    container_name: postgres-adminer  # Added consistent naming
    ports:
      # Keep Adminer port exposed so YOU can access it from your browser
      - "127.0.0.1:8080:9000"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres-backup  # Updated to match database container name
    depends_on:
      - database
    networks:
      # Ensure adminer is on the same network as postgres
      - pg_network

volumes:
  pg_data:
    name: postgres-backup-data  # Named volume for clarity

networks:
  pg_network:
    driver: bridge
    name: postgres-network  # More standard naming
