services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  backup:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      # Keep pgAdmin port exposed so YOU can access it from your browser
      - "127.0.0.1:8080:80"
    volumes:
      # Persist pgAdmin data and configuration
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_DISABLE_POSTFIX=true
    depends_on:
      - postgres
    networks:
      # Ensure pgAdmin is on the same network with postgres
      - pg_network

volumes:
  pg_data:
    name: postgres-data  # Named volume for clarity
  pgadmin_data:
    name: pgadmin-data  # Named volume for pgAdmin data

networks:
  pg_network:
    driver: bridge
    name: postgres-network  # More standard naming
