name: Build and push Docker images

on:
  push:
    branches: [ 'master' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push postgres image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.postgres-walg
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pg-with-backup:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pg-with-backup:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backup image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.backup
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pg-backup-walg:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pg-backup-walg:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
